services:
  mysql:
    build:
      context: ./mysql_docker
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test_db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
  nginx:
    build:
      context: ./nginx_docker
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx_docker/nginx.conf:/etc/nginx/nginx.conf:ro
#volumes:
#  mysql_data:
